############################################
# Config translations (and some fields) 
############################################
# common
nam: name # e.g. N.Y. Jets
des: description
sn: short name

# sport
spid: sport id

# league
lid: league id

# event
eid: event id
# cit: city
cou: country
es: event status
dt: datetime
st: stadium type

# participant
partid: participant id
ih: is home

# participant group
partgid: participant group id
nam: name

# team
nn: nickname
cit: location
tmid: team id
abbr: abbreviation
sta: stadium type
cou: country
conid: conference id
conname: conference name
divid: division id
divname: division name

# player
fn: first name
lnam: last name

# event group
egid: event group id
nam: name
alias: alias

# market
mtid: market id
mtids: market ids
url: url

# market group
mtgid: market group id

# market types
marketTypes: market types

# sportsbook
sbid: system sportsbook id
paid: sportsbook id

# consensus
wag: wagers
perc: percentage
tim: datetime

# search event
date: datetime
league: league
sport: sport
did: domain id

# line history
lines: lines

# league hierarchy
teamId: team id
seasonId: season id
leagueId: league id
id: id
name: name
shortname: short name
favoriteshortname: favorite short name

############################################
# Field translations
############################################
# lines
adj: spread / total
ap: american odds
pri: decimal odds

# event
eventGroup: event group
participants: participants
source: source
seid: season id

# score
pn: period
val: points scored

# event group
sdt: start datetime
edt: end datetime

# search event
# Using 'participants' so that match event queries (helpful in Lines._init_config()).
eventParticipants: participants
# this one doesn't matter because it's not used by Lines._init_config().
searchParticipants: search participants

# search league
region: region
rid: region id

# consensus
lineid: line id
line: line
wag: wagers
vol: volume
tvol: total volume
wb: whale bets