spid: 8
default market id: 126
consensus market ids:
  - 126
  - 395
  - 396

markets:
  - alias: ''
    marketTypes:
      - alias: Money Lines
        mtid: 126
        nam: 2way
        url: money-line
      - alias: Point Spreads
        mtid: 395
        nam: Point Spread
        url: pointspread
      - alias: Total Games
        mtid: 396
        nam: American Total
        url: totals
    mtgid: 217
    nam: Full Game
    url: full-game
    periods: 0
  - alias: Futures
    marketTypes:
      - alias: French Open Winner
        mtid: 719
        nam: French Open Winner
        url: french-open-winner
      - alias: Wimbledon Winner
        mtid: 720
        nam: Wimbledon Winner
        url: davis-cup-winner
      - alias: US Open Winner
        mtid: 721
        nam: US Open Winner
        url: us-open-winner
      - alias: Australian Open Winner
        mtid: 723
        nam: Australian Open Winner
        url: australian-open-winner
    mtgid: 224
    nam: Futures
    url: futures
