version: 2.1

jobs:
  build:
    # code runs inside this docker image, using python 3.9.0
    docker:
      - image: circleci/python:3.9.0
        # environment:
        #   TZ: 'UTC'

    # this is the default value
    working_directory: ~/project

    steps:
      # get code from Github
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: |
            pipenv run flake8 --max-line-length 88 --per-file-ignores="__init__.py:F401"
            pipenv run pytest -v --cov sbr
